function [fitresult, gof] = createFit(RPM, Tq, BSFCCase)
%CREATEFIT(RPM,TQ,BSFCCASE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : RPM
%      Y Input : Tq
%      Z Output: BSFCCase
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2016 10:44:37


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( RPM, Tq, BSFCCase );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'BSFCCase vs. RPM, Tq', 'Location', 'NorthEast' );
% Label axes
xlabel RPM
ylabel Tq
zlabel BSFCCase
grid on
view( -0.7, 90.0 );

% Make contour plot.
subplot( 2, 1, 2 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Contour' );
legend( h, 'untitled fit 1', 'BSFCCase vs. RPM, Tq', 'Location', 'NorthEast' );
% Label axes
xlabel RPM
ylabel Tq
grid on


