clear
mdl = 'test.emx';

xxsimConnect();
xxsimOpenModel(mdl);
xxsimProcessModel();

logVariables = {'time' ,...
    'Demux.output1',...
    'Demux.output2',...
    'Demux.output3',...
    'Demux.output4',...
    'Demux.output5',...
    'Demux.output6',...
    'Demux.output7',...
    'Demux.output8',...
    'Demux.output9'};
xxsimSetLogVariables(logVariables);

xxsimRun();
tic
[values, names] = xxsimGetLogValues(logVariables);
toc